---
stages:
  - deploy
variables:
  KUBECONFIG:
    description: "Kubernetes config folder"
    value: "/home/gitlab-runner/.kube"
  NAME_HELM_CHART:
    description: "Kubernetes config folder"
    value: "appchart"  
deploy:
  stage: deploy
  before_script:
    - kubectl get pods
  script:
    - helm upgrade -i ${NAME_HELM_CHART} ./
  after_script:
      - echo "Cleaning up"
      - rm -rf ${CI_PROJECT_DIR}
  tags:
    - helm
