apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $.Release.Name | lower }}-config
data:
  {{ .Values.appchart.NginxDomain }}: |-
    server {
        listen {{ .Values.appchart.port | default "80" }};
        server_name  {{ .Values.appchart.NginxDomain }} www.{{ .Values.appchart.NginxDomain }};
        access_log  /var/log/nginx/{{ .Values.appchart.NginxDomain }}-access.log  main;
        error_log   /var/log/nginx/{{ .Values.appchart.NginxDomain }}-error.log info;
        location / {
            include proxy_params;
            proxy_pass http://127.0.0.1:{{ .Values.appchart.port | default "80" }}/;
        }
    }
